# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d7ec3f22af309df10f0c8a2cadff25da96107f3e21182369e247bc3cacc0c54210891e266d0ae38ca0d1eb05e9c49d839b1196c4e305346296a71c4cd3916dd

test:
  secret_key_base: 66727a532f77f04ef6a03b68251c506f29fe8f19bd29aed90cb9a2a1109418e7d6ccb30646905806c64d4f0aa5a61ab7bb0c33b616f393e8ac1295044d8000f5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
